apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cos
  name: cadvisor-selector
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: true
      port: http
  namespaceSelector:
    matchNames:
      - cadvisor
  selector:
    matchLabels:
      app: cadvisor
