apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: cos
  name: cos-fleetshard-sync-selector
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /q/metrics
      port: web
      honorLabels: true
  namespaceSelector:
    matchNames:
      - redhat-openshift-connectors
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-sync
      app.kubernetes.io/part-of: cos
