apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cos
  name: node-exporter-selector
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      targetPort: 9100
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
