apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-operator-pod-selector
  namespace: redhat-openshift-connectors
  labels:
    app: cos
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: http
  selector:
    matchLabels:
      app: strimzi