apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: server
  namespace: redhat-openshift-connectors
spec:
  podMonitorSelector:
    matchLabels:
      app: cos
  serviceMonitorSelector:
    matchLabels:
      app: cos
  serviceAccountName: prometheus