apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-server
  namespace: monitoring
spec:
  config:
    log:
      level: error
      mode: console
  service:
    labels:
      app: grafana
      type: grafana-service
    name: grafana-service