kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-grafana
  namespace: redhat-openshift-connectors
spec:
  rules:
    - host: grafana-server
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
