apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafana-datasource
  namespace: redhat-openshift-connectors
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      type: prometheus
      url: 'http://prometheus-server'
      version: 1
  name: middleware.yaml