apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/grafana-operator.redhat-openshift-connectors: ''
  name: grafana-operator
  namespace: redhat-openshift-connectors
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: operatorhubio-catalog
  sourceNamespace: olm