apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: cos
  name: cos-fleetshard-operator-camel-selector
  namespace: redhat-openshift-connectors
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /q/metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-operator-camel
      app.kubernetes.io/part-of: cos
